export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";

export const MY_ORDER_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDER_FAILURE = "MY_ORDERS_FAILURE";

export const GET_All_ORDERS_REQUEST = "GET_All_ORDERS_REQUEST";
export const GET_All_ORDERS_SUCCESS = "GET_All_ORDERS_SUCCESS";
export const GET_All_ORDERS_FAILURE = "GET_All_ORDERS_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
