export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const TOGGLE_WISHLIST_REQUEST = "TOGGLE_WISHLIST_REQUEST";
export const TOGGLE_WISHLIST_SUCCESS = "TOGGLE_WISHLIST_SUCCESS";
export const TOGGLE_WISHLIST_FAIL = "TOGGLE_WISHLIST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
